### ISSUE TITLE
Add "rememberDevice" parameter to OktaFactor.verify() functions - need it 9/23/2019

### ISSUE THREAD

**Issue by efeluke** [okta/okta-auth-swift#106]
Currently, "rememberDevice" is supported in OktaAPI.verifyFactor() function, however, it is not available in top public function OktaFactor.verify() so users can't use "rememberDevice" feature.

We plan to release our first version of mobile app for supporting Okta in 3 weeks, it would be great to have the fix by 9/23.  Thanks.

**Comment by IldarAbdullin-okta** [comment]
Please refer to https://github.com/okta/okta-auth-swift/issues/105 for explanation why it is not implemented in the SDK
