### ISSUE TITLE
oktaOidc.signOutOfOkta() function should not make UIViewController as a required parameter

### ISSUE THREAD

**Issue by efeluke** [okta/okta-auth-swift#107]
https://developer.okta.com/docs/guides/sign-users-out/ios/sign-out-of-okta:

public func signOutOfOkta(_ authStateManager: OktaOidcStateManager,
                                    from presenter: UIViewController,
                                    callback: @escaping ((Error?) -> Void))

We just want to logout user and clear Okta session & tokens quietly (no UI / user interaction is needed).  Can we do that without passing a UIViewController?

**Comment by IldarAbdullin-okta** [comment]
Hi @efeluke ,

If you want to clear Okta session(delete persistent cookie) then you have to call `signOutOfOkta` function. It uses `ASWebAuthenticationSession` class that requires `UIViewController` context and it also shows message box with warning message.
If you want to remove persistent cookie silently, then probably you can try to delete cookie from cookie storage using `HTTPCookieStorage` class
Tokens can be revoked silently as this is just a set of REST calls

Ildar

**Comment by efeluke** [comment]
Okta Android SDK has oidcAuthClient.signOut() function which doesn't need any UI.  Can we do the same in the iOS version?

**Comment by IldarAbdullin-okta** [comment]
iOS and Android have different implementation details. Please see my previous comment.
iOS implementation is OIDC compliant

**Comment by efeluke** [comment]
What did you mean by "Tokens can be revoked silently as this is just a set of REST calls"?  Do we need to make network calls to some REST APIs directly (not from the SDK)?

**Comment by IldarAbdullin-okta** [comment]
Please call `revoke` API from the SDK

**Comment by Tigerspike-A** [comment]
`revoke` does not sign the user out of browser though.
also, using SwiftUI hence there is not presenting UIViewController. How shall we handle this situation?
