### ISSUE TITLE
Add name property to Profile struct

### ISSUE THREAD

**Issue by efeluke** [okta/okta-auth-swift#109]
When user is on Okta Verify screen, we'd like to show the device name the user should use to run "Okta Verify" app.  Adding "name" property to Profile struct should solve the problem:

public struct Profile: Codable {
            public let name: String?
            public let phoneNumber: String?
            ...
}

**Comment by Mohitkiran** [comment]
Hi @IldarAbdullin-okta ,

Can I know an ETA on this enhancement?

Thank you

**Comment by IldarAbdullin-okta** [comment]
Hi @Mohitkiran ,

Let me address this on next week. I will let you know

Ildar

**Comment by IldarAbdullin-okta** [comment]
Fixed in 2.2.0 release
https://github.com/okta/okta-auth-swift/releases/tag/2.2.0
