### ISSUE TITLE
Update Project Settings to Support iOS 11.0 

### ISSUE THREAD

**Issue by hwallander86** [okta/okta-auth-swift#110]
Customer requires support for iOS 11.0 

Currently customer is getting following error: Compiling for iOS 11.0, but module 'OktaAuthNative' has a minimum deployment target of iOS 12.1.

Please update project settings to support iOS 11.0 or earlier.

**Comment by IldarAbdullin-okta** [comment]
https://github.com/okta/okta-auth-swift/pull/111

**Comment by IldarAbdullin-okta** [comment]
Fixed on master branch. iOS target is 10.0 now
