### ISSUE TITLE
OktaOidcKeychain.clearAll() deletes app related keychain entries

### ISSUE THREAD

**Issue by Dozer1170** [okta/okta-auth-swift#114]
**Describe the bug**
When OktaOidcKeychain.clearAll() is called, it also deletes any items the app may have stored in the keychain.

**To Reproduce**
1. Save an item in the keychain in the default access group
2. Call OktaOidcKeychain.clearAll()
3. Get errSecItemNotFound when trying to retrieve your keychain item

**Expected behavior**
OktaOidcKeychain.clearAll() should only clear Oidc related items from the keychain.

**Desktop (please complete the following information):**
 - OS: iOS
 - Version: 11-13

**Smartphone (please complete the following information):**
 - Device: iPhone X, iPad Mini, iPhone Xs Plus
 - OS: 13.3

**Additional context**
This caused a difficult to track down issue in our app. We would login with okta auth. Store an internet password in the keychain. Logout of the app which would call OktaOidcKeychain.clearAll(). Then try to login using the stored internet password, which had just been deleted by Okta.

**Comment by IldarAbdullin-okta** [comment]
Wrong repo. Please create issue in https://github.com/okta/okta-oidc-ios repo
