### ISSUE TITLE
Not able to add Okta Auth SDK in MacOS project.

### ISSUE THREAD

**Issue by Mohitkiran** [okta/okta-auth-swift#115]
**Description:**
I am trying to include Okta-Auth-SDK in MacOS bundle project using cocoapods, and when I do `pod install` I am getting the following error `[!] The platform of the target 'SampleBundle' (macOS 10.15) is not compatible with 'OktaAuthSdk (2.0.2)', which does not support 'macOS'.`

**Pod File:**

```
target 'SampleBundle' do
  	use_frameworks!
	platform :osx, '10.15'
	pod 'OktaAuthSdk'
end
```

**Conclusion:**

So, how can I include this in a macos application? Where am I doing wrong?

**Comment by IldarAbdullin-okta** [comment]
Hi @Mohitkiran ,

Unfortunately current SDK podspec supports only iOS. Let us add macOS support. I will keep you posted

Ildar

**Comment by Mohitkiran** [comment]
Any ETA on this?

**Comment by IldarAbdullin-okta** [comment]
@Mohitkiran , sorry for late response. Let me address this issue on this week

**Comment by IldarAbdullin-okta** [comment]
Hi @Mohitkiran ,

New version 2.1.0 has been released via cocoapods. Could you try the lib in your MacOS project? Please let me know if you need Carthage support, we can add it as well

Ildar

**Comment by Mohitkiran** [comment]
Awesome, thanks I will let you know after I try it.
