### ISSUE TITLE
UI TESTS BUG

### ISSUE THREAD

**Issue by saulurias** [okta/okta-auth-swift#118]
**Describe the bug**
Not being able to find the textfields from the webview, took the code from your examples and it used to work but now did stop working.

**To Reproduce**
1. run the UI Tests

**Expected behavior**
The tests should be success

**Screenshots**
<img width="1028" alt="Screen Shot 2020-02-09 at 12 05 59" src="https://user-images.githubusercontent.com/11281932/74107365-abbe9d00-4b34-11ea-87fd-0644fa2e7a51.png">

**Smartphone (please complete the following information):**
 - Device: [iPhone 11 Pro Max]
 - OS: [e.g. iOS13.3]
 - Browser [safari]

**Comment by IldarAbdullin-okta** [comment]
Hi @saulurias ,

I suspect that you see this issue in `samples-ios` repo. Could you copy this issue into samples repo?

Ildar
