### ISSUE TITLE
[Feature request] Swift Package Manager support. 

### ISSUE THREAD

**Issue by lakersr8ers** [okta/okta-auth-swift#119]
Our team uses [Swift Package Manager](https://swift.org/package-manager/) and noticed that there is no way of consuming this package via SwiftPM. At the moment we would have to pull down the source or generate a framework and include it into our package manually :( 

The ask here is to configure this github package so that I (and other SwiftPM users now and in the future) can pull down this package using Swift package manager.

**Comment by lakersr8ers** [comment]
Looking at your podspec there doesn't seem to be any external dependencies so this task should hopefully be trivial (unless i'm missing something). 

**Package@swift-5.0.swift**

    // swift-tools-version:5.0
    import PackageDescription

    let pkg = Package(name: "OktaAuthNative")
    pkg.platforms = [
        .macOS(.v10), .iOS(.v10)
    ]
    pkg.products = [
        .library(name: "OktaAuthNative", targets: ["OktaAuthNative iOS"]),
    ]

    let oktaAuth: Target = .target(name: "OktaAuthNative iOS")
    oktaAuth.path = "Source"
    oktaAuth.exclude = [
        "Source/Info.plist" # not sure if this is needed
    ]
    oktaAuth.swiftLanguageVersions = [.v4_2, .v5]
    pkg.targets = [
        oktaAuth,
        .testTarget(name: "OktaAuthNative iOS Tests", dependencies: ["OktaAuthSdk"])
    ]

**Comment by IldarAbdullin-okta** [comment]
Hi @lakersr8ers ,

Thanks for this feature request. Unfortunately SPM support is not currently in our roadmap. However you are always welcome to contribute to the repo! ❤️ 

Ildar

**Comment by zocario** [comment]
Hi, I was wondering if integration of SPM was supported or not?

I've seen this old PR: https://github.com/okta/okta-auth-swift/pull/99 which is supposed to add SPM support but I don't see it in master branch? What is the current status for this? 

Thanks :)

**Comment by ThomasLeblond** [comment]
Hello @IldarAbdullin-okta any news about the support of SPM?

**Comment by oleggnidets-okta** [comment]
Hi guys, 
Please, check out the latest version. SPM is added.
