### ISSUE TITLE
Not getting call back (completion handler not executed) from OktaAuthSdk.authenticate()

### ISSUE THREAD

**Issue by Mohitkiran** [okta/okta-auth-swift#121]
**Description**
I am working on bundle project in macOS which is a [`authorization plugin`](https://developer.apple.com/documentation/security/authorization_plug-ins/using_authorization_plug-ins) and it runs during log in

So when I am using `OktaAuthSdk.authenticate` the completion handler is never getting executed, **but this works completely fine and as expected in case of a normal cocoa application for macOS the problem persists with Bundle project.**

The completion handler gets executed when I comment out `DispatchQueue.main.async` from `OktaAPIRequest.run()` when not commented the code block inside `DispatchQueue.main.async` is never getting executed. Even though it is getting executed when I comment out `DispatchQueue.main.async` the problem is execution is not happening from the main thread and I am doing UI updates in the completion handler and this is causing issues with UI.

Don't know where I am going wrong, Let me know if you need more info or any code samples.

Thank you.

**Environment:**
OS: macOS Mojave (10.14.5)
Swift: 4.2
Xcode: 11.2.1

**Comment by IldarAbdullin-okta** [comment]
Hi @Mohitkiran ,

I believe closure is never called on main thread because main thread is blocked. Can you check in the debugger what main thread is doing? Probably some blocking network or db read/writes, or some deadlock happened in your app

Ildar

**Comment by Mohitkiran** [comment]
Hi IIdar,

I checked and there is no deadlock happening and also if I make one change in SDK i.e change DispatchQueue.main.async to [performSelector](https://developer.apple.com/documentation/objectivec/nsobject/1414900-performselector) then callback is getting called and everything is working fine.

**Comment by Mohitkiran** [comment]
Figured out what's causing the issue, I am using `NSApp.runModal(for: windowController.window!)` to open and show the UI and `DispacthQueue.main.async` NSApp is running modal view on the main queue with a block and GCD is having an issue re-entering the main queue.  performSelectorOnMainThread, however, is going directly to the main run loop and is not having an issue in this context.

**Comment by IldarAbdullin-okta** [comment]
Hi @Mohitkiran ,

I'm happy that you found the issue. Probably `DispacthQueue.main` queue was overloaded with UI events and therefore AuthSwift lib had not have a chance to execute its block? Or you think there is an issue inside `DispacthQueue.main` implementation?

Ildar

**Comment by Mohitkiran** [comment]
Hi @IldarAbdullin-okta 

The issue I faced is a result of the window being run in a modal run loop i.e `NSApp.runModal(for: windowController.window!)`. In this context, the modal event loop for the specified window runs synchronously and I guess this is causing the issue for the `DispacthQueue.main.async` block in `OktaAPIRequest` to get executed however when I used` windowController.showWindow(windowController)` to open the window solved the issue, not sure if that's something Apple needs to mention in their documentation or handle it internally in the implementation of `GCD`.

Mohit
