### ISSUE TITLE
Please add error code to callback closure error object.

### ISSUE THREAD

**Issue by Mohitkiran** [okta/okta-auth-swift#122]
Hi @IldarAbdullin-okta 

Can you please add [error code](https://developer.okta.com/docs/reference/error-codes/) along with error description in error object returned in call back closure. I want to differentiate recoverable errors and non-recoverable errors basing on error codes.

For example, I want to treat authentication failed as a non-recoverable error I want my application to be terminated in this case.

Thank you

**Comment by IldarAbdullin-okta** [comment]
Hey @Mohitkiran ,

Why `OktaAPIErrorResponse` is not enough for your needs? It contains a bunch of error info along with `errorCode` and `errorSummary`

Ildar

**Comment by Mohitkiran** [comment]
My bad, you are right `OktaAPIErrorResponse` would suffice the needs. Closing this.

Thank you,

**Comment by x-yurii-uvarov** [comment]
Hi @IldarAbdullin-okta ,
Sorry, but I have the same question, how to get the error code from auth method if it failed?
I invoke [OktaAuthSdk.authenticate](https://github.com/okta/okta-auth-swift/blob/b8ba74c1a603af60ef8b1b3817ce6c7b00fad2a9/Source/OktaAuthSdk.swift#L17) and [onError](https://github.com/okta/okta-auth-swift/blob/b8ba74c1a603af60ef8b1b3817ce6c7b00fad2a9/Source/OktaAuthSdk.swift#L21) function returns the [OktaError](https://github.com/okta/okta-auth-swift/blob/b8ba74c1a603af60ef8b1b3817ce6c7b00fad2a9/Source/OktaError.swift#L15) instance, not [OktaAPIErrorResponse](https://github.com/okta/okta-auth-swift/blob/4e0c02ff7d2a168c489b42326ebdab759c3cab77/Source/DomainObjects/OktaModels.swift#L99). 

What I'm doing wrong and how to get the error code?

**Comment by oleggnidets-okta** [comment]
Hey @x-yurii-uvarov 
You retrieve a specific error using `switch case` statement. `OktaAPIErrorResponse` appears on [`.serverRespondedWithError`](https://github.com/okta/okta-auth-swift/blob/b8ba74c1a603af60ef8b1b3817ce6c7b00fad2a9/Source/OktaError.swift#L21) case.
