### ISSUE TITLE
Xcode 12 Support 

### ISSUE THREAD

**Issue by Shagans982** [okta/okta-auth-swift#134]
When is Xcode 12 support coming?

**Comment by IldarAbdullin-okta** [comment]
Hi @Shagans982 ,

What issues you have with XCode 12? I've successfully built the library in XCode 12.0.1

Ildar

**Comment by Shagans982** [comment]
Im using Carthage when when I attempt to rebuild the projects `carthage build` the console tells me it cannot because the project itself (ie the check-out project) doesn't compile. 

*** Building scheme "OktaAuthNative iOS" in OktaAuthSdk.xcworkspace
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/shagans/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/okta-auth-swift/2.2.0/Build/Intermediates.noindex/ArchiveIntermediates/OktaAuthNative\ iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OktaAuthNative.framework/OktaAuthNative /Users/shagans/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/okta-auth-swift/2.2.0/Build/Products/Release-iphonesimulator/OktaAuthNative.framework/OktaAuthNative -output /Users/shagans/careconsult/Carthage/Build/iOS/OktaAuthNative.framework/OktaAuthNative

This usually indicates that project itself failed to compile. Please check the xcodebuild
