### ISSUE TITLE
Unable to get name(name of the device) from push factor's profile

### ISSUE THREAD

**Issue by Sukanya941** [okta/okta-auth-swift#138]
**App is getting crashed while trying to print device name in push**

**Comment by oleggnidets-okta** [comment]
Hi @ Sukanya941,
Could you, please, share some steps to reproduce.

**Comment by Sukanya941** [comment]
Sure.. 
**To Reproduce**

- Create a factor(pushFactor) that implements **OktaFactorPush** .
- Fetch the Device Name using pushFactor.profile.name (unwrap or make it optional if needed).
- Get error that says **Value of type 'EmbeddedResponse.Factor.Profile' has no member 'name'**.

**Expected Behaviour** 
Should get the name for the device with which you've enrolled for push MFA.

**Additional Information**
Xcode Version - Version 11.3 (11C29) and Version 12.3 (12C33)
OS - MacOS Big Sur 11.2.3 (20D91), MacOS Catalina 10.15.1

**Comment by oleggnidets-okta** [comment]
Internal task is recorded, OKTA-390476. It's not in priority for time being, I believe we'll take in progress it soon. 
Thanks for reporting!

**Comment by oleggnidets-okta** [comment]
Hi @Sukanya941,
I'm working on the issue right now. So far, I couldn't reproduce the issue, I can get the device name by `pushFactor.profile.name`. I use repo' sample app. 

<img width="292" alt="okta authn" src="https://user-images.githubusercontent.com/77254185/117168879-3b530a00-add1-11eb-9022-63803268cfbf.png">

> App is getting crashed while trying to print device name in push 

Have you tried to put `print` in code? 
For some reason, Xcode throws the error while I'm trying to use debugger. But when I put `print` in code I can see the value. So you can try too.

**Comment by oleggnidets-okta** [comment]
Closing as no response from the author. 
@Sukanya941 Feel free to reopen and share additional information.
