### ISSUE TITLE
Date string does not match format expected by formatter.

### ISSUE THREAD

**Issue by roneloza** [okta/okta-auth-swift#141]
**Describe the bug**
Date string does not match format expected by formatter.

**To Reproduce**
1. Launch the Settings app.
2. Tap General.
3. Tap Date & Time.
4. Tap on the Off switch next to 24-Hour Time.

**Additional context**

ERROR: Authentication failed with error: responseSerializationError(Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "_embedded", intValue: nil), CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "passwordChanged", intValue: nil)], debugDescription: "Date string does not match format expected by formatter.", underlyingError: nil)), 1172 bytes)

https://github.com/okta/okta-auth-swift/blob/master/Source/RestAPI/OktaAPIRequest.swift
```swift
public init(baseURL: URL,
                urlSession: URLSession,
                httpClient: OktaHTTPRequestListenerProtocol? = nil,
                completion: @escaping (OktaAPIRequest, Result) -> Void) {
        self.baseURL = baseURL
        self.urlSession = urlSession
        self.httpClient = httpClient
        self.completion = completion
        decoder = JSONDecoder()
        
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        decoder.dateDecodingStrategy = .formatted(formatter)
    }
```

Force use locale is a possible solution
```swift
let dateFormatter = DateFormatter()
    dateFormatter.locale = Locale(identifier: "en_US_POSIX")
    dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    if let date = dateFormatter.date(from: "2020-09-08T19:57:04.000Z") {
      print(dateFormatter.string(from: date))
    } else {
      print("There was an error decoding the string")
    }
```

**Comment by mikenachbaur-okta** [comment]
Hi @roneloza, were you able to verify that the forced locale change addressed your issue? If you have a local change, you could always submit a PR if you have a fix for this. Otherwise we'll be looking into this shortly.

Cheers!

**Comment by roneloza** [comment]
Hi @mikenachbaur-okta 
PR: https://github.com/okta/okta-auth-swift/pull/142

Cheers!

**Comment by hashans** [comment]
@roneloza Was facing the same issue. Your fix works. Force locale setting.

**Comment by mikenachbaur-okta** [comment]
Hi @roneloza and @hashans, I was able to reproduce this bug and verified that your fix works great. Thank you!

**Comment by roneloza** [comment]
Hi @mikenachbaur-okta. Can you generate a new tag? to be able to make a carthage okta-auth-swift in my local project and stop using my fork

**Comment by mikenachbaur-okta** [comment]
@roneloza I just pushed a new tag, I hope this works for you.  Thank you for your patience!
