### ISSUE TITLE
Apple Device Check

### ISSUE THREAD

**Issue by andrewvanbeek-okta** [okta/okta-auth-swift#144]
Hi all, I was wondering if this SDK supports apple Device Check mentioned here: https://developer.apple.com/documentation/devicecheck.  If not are there any examples or integration patterns?

**Comment by oleggnidets-okta** [comment]
Hi @andrewvanbeek-okta,
I suggest not to duplicate the question and discuss it in scope of https://github.com/okta/okta-oidc-ios/issues/272 .

I close for now. It will be re-open if necessary.
