### ISSUE TITLE
[PKCE] How to set authentication state from accessToken and refreshToken

### ISSUE THREAD

**Issue by apersaud** [okta/okta-auth-swift#147]
I’m using the OktaOidc (v3.10.2) and OktaAuthNative (v2.4.2) SDKs on iOS to login a user through an SSO flow (PKCE). Our SSO process has the backend performing the authentication and providing the final accessToken and refreshToken for the clients to use.

The only two APIs available for us on the iOS SDK seems to be `OktaAuthSdk.authenticate(with: url, username: username, password: password)` and `OktaOidc().authenticate(withSessionToken: token)`. However, our backend system calls /v1/authorize and /v1/token on our behalf and provide the native app the refresh and access tokens they should use going forward. Is there a way to set these in the SDK directly or a way to create an OktaOidcStateManager from just this information?

https://github.com/okta/okta-oidc-ios/issues/295

https://devforum.okta.com/t/ios-sdk-pkce-how-to-set-authentication-state-from-accesstoken-and-refreshtoken/14403

**Comment by oleggnidets-okta** [comment]
Hi @apersaud ,

Thanks for reporting the issue. I close it, as it seems [duplicated](https://github.com/okta/okta-oidc-ios/issues/295) in okta-oidc-ios repository.
