### ISSUE TITLE
SDK Documentation for Forgot Password Email Factor

### ISSUE THREAD

**Issue by Good-man** [okta/okta-auth-swift#148]
The documentation for forgot password located [here](https://github.com/okta/okta-auth-swift#forgot-password) could use improvement. 

The SDK docs do not mention needing to exchange the recovery token for a state token prior to calling fetchStatus.  The [verify recovery token](https://developer.okta.com/docs/reference/api/authn/#verify-recovery-token) API can be used to exchange these tokens, but apparently this is not implemented in the SDK.

I'm told that [Primary authentication with activation token](https://developer.okta.com/docs/reference/api/authn/#primary-authentication-with-activation-token) API can also be used, but I have not verified this.

**Comment by oleggnidets-okta** [comment]
Hi @Good-man,

Thank you for reporting the issue!

Do you mean forgot password may be be done through activation token? Would you, please, clarify in more details?

btw, you may create the PR and our team will review it.

**Comment by oleggnidets-okta** [comment]
I believe the issue may be closed. If you still has the concern about documentation, please, re-open the issue or contribute to our README.

Thank you!
