### ISSUE TITLE
OktaError's localizedDescription might not be working as intended

### ISSUE THREAD

**Issue by JeremyChiang** [okta/okta-auth-swift#156]
**Describe the bug**
Calling `error.localizedDescription` in the client code doesn't actually return the more detailed `NSLocalizedString(self.description, comment: "")` from OktaError.

Instead of getting `Your token doesn't match our records. Please try again.`, you'd get `The operation couldn’t be completed. (OktaAuthNative.OktaError error 2.)`, which seems like it's an error description from `URLSession`?

I am a bit confused by Swift's Error protocol as well. However, it looks like you need to adopt the `LocalizedError` protocol instead of just overriding the `localizedDescription` property that's also available in `Error`. If this is true, I am not sure why or what the `localizedDescription` property in `Error` is for, or why or how `URLSession`'s description might be overtaking our own description (if this is even true) 😅 If anybody also knows more, I'd love to learn more.

Based on this discussion https://forums.swift.org/t/confusing-error-localizeddescription-output/5337 it might be because the `localizedDescription` in `Error` is meant to help Swift internally convert/dispatch to NSError behind the scene, so it is (probably) not meant to be overridden. This might explain why we ended up getting `URLSession`'s interpretation of the error since we don't have our own definition for `LocalizedError`.

**To Reproduce**
```
smsFactor.verify(
    passCode: code,
    onStatusChange: { [weak self] newStatus in
        // do stuff
    },
    onError: { [weak self] error in
        guard let self = self else { return }
        self.showError(error.localizedDescription)
    }
)
```

**Expected behavior**
`error.localizedDescription` should return the string from :
```
var localizedDescription: String {
    return NSLocalizedString(self.description, comment: "")
}
```
...but instead we'd get:
`The operation couldn’t be completed. (OktaAuthNative.OktaError error [a number here].)`

**Comment by oleggnidets-okta** [comment]
Hey @JeremyChiang 

Thanks for detailed issue!

We've just released a new [version 2.4.3](https://github.com/okta/okta-auth-swift/releases/tag/2.4.3). `OktaError` conforms to `LocalizedError` now. Also, if you want to get better understanding of the error I would suggest `switch case` statement, like this:

```swift
smsFactor.verify(
    passCode: code,
    onStatusChange: { [weak self] newStatus in
        // do stuff
    },
    onError: { [weak self] error in
        guard let self = self else { return }
        switch error {
            case .unexpectedResponse: {your code}
            case .alreadyInProgress: {your code}
            // etc.
        }
    }
)
```

**Comment by JeremyChiang** [comment]
Thank you for the swift reply and update! I have tested and verified that this issue is now fixed 🎉

**Comment by oleggnidets-okta** [comment]
@JeremyChiang You're welcome. We always glad to help!
