### ISSUE TITLE
How should links be handled?

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-auth-swift#22]
The Authentication API returns contextual links for many states (inspired by [HAL](http://stateless.co/hal_specification.html)).

See: https://developer.okta.com/docs/api/resources/authn#transaction-state

For example, the `verify` link in [this response](https://developer.okta.com/docs/api/resources/authn#response-example-for-primary-authentication-with-public-application-factor-challenge) indicates where the client should POST to in order to verify the specified MFA factor.

How should we make it easy for the developer to use these links when writing code that interacts with this SDK? We should encourage developers to use the links, rather than hard-coding paths into their application (or using hard-coded paths in this SDK).

For reference, Auth.js (our equivalent library for JS) enriches the response objects with "smart" methods that follow these links: https://github.com/okta/okta-auth-js#mfa_challenge

cc @robertjd @bdemers @FeiChen-okta @laura-rodriguez for discussion

**Comment by IldarAbdullin-okta** [comment]
Will be handled by Release 1.0.0

**Comment by IldarAbdullin-okta** [comment]
Resolved in version 1.0.0
