### ISSUE TITLE
How does refresh token Work?

### ISSUE THREAD

**Issue by codal-ashahu** [okta/okta-auth-swift#50]
Hi, the Objective-C SDK had a refresh token method as shown here: https://github.com/okta/okta-sdk-appauth-ios#refresh

> Since access tokens are traditionally short-lived, you can refresh expired tokens by exchanging a refresh token for new ones. See the configuration reference to ensure your app is configured properly for this flow.

> OktaAuth
>   .refresh()
>   .then { newAccessToken in
>     print(newAccessToken)
>   }
>   .catch { error in
>     // Error
>   }
> 

Is there any similar feature on this new SDK? how do we refresh the access and ID token if we do have offline_access scope?

Thanks.

**Comment by IldarAbdullin-okta** [comment]
Hi @codal-ashahu,

     This sdk doesn't provide requested functionality. So in order to get access/refresh tokens you have to use both SDK's - OktaAppAuth and OktaAuthSwift. So the sequence of actions would be:
1. Authenticate user via OktaAuthSwift SDK and get session token
2. Exchange session token to access/refresh tokens via OktaAppAuth SDK(use `authenticate(withSessionToken sessionToken: String)` function)

If your project doesn't have strict UI requirements I would personally recommend to use OktaAppAuth SDK and use browser-based sign-in

Let me know if you need more details!
