### ISSUE TITLE
How to access web page using okta auth from native webview

### ISSUE THREAD

**Issue by Ranjit7373** [okta/okta-auth-swift#75]
I have integrated OktaAuth sdk successfully and get accessToken, idToken, refreshToken.
I want to load one web page from native which requires okta signin, My issue is I want to load the web page using the same session details from native, but it shows me okta login page.
 Can any one help me to do this.

**Comment by IldarAbdullin-okta** [comment]
Hi @Ranjit7373 ,

Unfortunately it is not possible to share session token with webkit or SafariBrowser. Server invalidates session token once you exchange it to access token

Ildar

**Comment by IldarAbdullin-okta** [comment]
Hi @Ranjit7373 ,

Solution for the issue has been found and will be addressed in https://github.com/okta/okta-auth-swift/issues/98

Thanks!
