### ISSUE TITLE
Swift version error

### ISSUE THREAD

**Issue by mdeveracoding** [okta/okta-auth-swift#82]
All, I have updated my Podfile as directed in your instructions.  But when I run pod install I get...

[!] Unable to determine Swift version for the following pods:

- `OktaAuthSdk` does not specify a Swift version and none of the targets (`XXX`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Here is what I have in my Podfile.  I have tried swift_version 3.0 and 5.0 but no avail.

pod 'OktaAuthSdk', '~> 2.0'

and 

post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'OktaAuthSdk'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.0'
              end
         end
      end
end

**Comment by IldarAbdullin-okta** [comment]
Hi @mdeveracoding ,

I think you can resolve this by adding empty `.swift` file into your project. Or try to add the following into your `podfile`:

pre_install do |installer|
installer.analysis_result.specifications.each do |s|
        if s.name == 'OktaAuthSdk'
            s.swift_version = '4.2'
        end
    end
end

I will also update `.podspec` to explicitly set swift version

**Comment by mdeveracoding** [comment]
IldarAbdullin-okta, thank you!  The second solution for the pre_install worked for me.  I did not create an empty .swift file.

**Comment by mdeveracoding** [comment]
Closing issue since you resolved my problem.  Thanks again IldarAbdullin-okta!
