### ISSUE TITLE
Incompatible versions for pod "OktaAuthSdk"

### ISSUE THREAD

**Issue by mdeveracoding** [okta/okta-auth-swift#84]
When I try running pod install I get the error below (see item 1).  Is there an issue with compatibility between react-native-vector-icons and the OktaAuthSdk?  I have also included a copy of my Podfile (see item 2).

1. Error from pod install....

$ pod install
Analyzing dependencies
Fetching podspec for `RNVectorIcons` from `../node_modules/react-native-vector-icons`
[!] CocoaPods could not find compatible versions for pod "OktaAuthSdk":
  In Podfile:
    OktaAuthSdk

Specs satisfying the `OktaAuthSdk` dependency were found, but they required a higher minimum deployment target.

2. Podfile

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XXX' do
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  pod 'OktaAuthSdk'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AppAuth', '= 0.95'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'XXX' do
    inherit! :search_paths
    # Pods for testing
  end
end

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    if s.name == 'OktaAuthSdk'
      s.swift_version = '4.2'
    end
  end
end

**Comment by IldarAbdullin-okta** [comment]
Hi @mdeveracoding ,

Error shows that `OktaAuthSdk` is not compatible with iOS 9.0. Minimum iOS version for the library is 10.0

Ildar

**Comment by mdeveracoding** [comment]
@IldarAbdullin-okta,  Thanks I see that I needed to add the change below in the podfile.

platform :ios, '10.0'
