### ISSUE TITLE
Examples of Testing / Mocking available?

### ISSUE THREAD

**Issue by nodediggity** [okta/okta-auth-swift#86]
I have looked on the docs but had no luck, I am trying to find some more information on how best to mock this pod for testing.

I have written a service that provides an abstraction over the 3 okta pods I am using:

```
  pod 'OktaAuthSdk',    :inhibit_warnings => true
  pod 'OktaOidc',       :inhibit_warnings => true
  pod 'OktaStorage',    :inhibit_warnings => true
```

As the SDK is essentially a singleton, my normal approach would be as follows:

1. Create a protocol that has the methods on the singleton I want
```swift
import OktaAuthSdk

protocol OktaAuthSdkType: class {
    static func authenticate(with url: URL, username: String, password: String?, onStatusChange: @escaping (_ newStatus: OktaAuthStatus) -> Void, onError: @escaping (_ error: OktaError) -> Void)
    static func recoverPassword(with url: URL, username: String, factorType: OktaRecoveryFactors, onStatusChange: @escaping (_ newStatus: OktaAuthStatus) -> Void, onError: @escaping (_ error: OktaError) -> Void)
}
```
2. Make the 3rd party (Okta) singleton conform to my protocol via an extension
```swift
extension OktaAuthSdk: OktaAuthSdkType { }
```
3. Use my protocol as the type on my class / struct
```swift
public class OAuthService: OAuthServiceType {

   private var oktaAuthSDK: OktaAuthSdkType
   ......
}
```
4. Inject a mock service conforming to the same protocol when testing
```swift
let sut = OAuthService(adminSDK: MockAdminSDK())
```

This works in most cases, however in this instance I am not able to take approach as I cannot instantiate `OktaAuthSdk`  either via constructor injection nor via sub classing and overriding the methods I would like to assert against due to the 'singleton' instance using `static class` methods and also have a `public` access modifier.

I was able to partly get around this using a generic on my service

```swift
public typealias OAuthService = OAuthServiceEngine<OktaAuthSdk>
public class OAuthServiceEngine<AdminSDK: OktaAuthSdkType>: OAuthServiceType { }
```

However this approach does not lend itself well when also needing to mock `OktaOidc` as this can throw on `init`.

**Comment by IldarAbdullin-okta** [comment]
@nodediggity , `OktaAuthSdk` is just a helper class that helps you to instantiate `OktaAuthStatusUnauthenticated` instance with the default parameters. If you need mocking capabilities I would probably do the following:
- Subclass from `OktaAuthStatusUnauthenticated` and create `OktaAuthStatusUnauthenticatedMock` class, override required methods. Override other status classes if required. Subclass from `OktaAuthStatusResponseHandler` and implement your own `OktaAuthStatusResponseHandlerMock` class. You can also mock `OktaAPI`class and feed to mocked status class
- Implement factory that will build `OktaAuthStatusUnauthenticated` or `OktaAuthStatusUnauthenticatedMock` instance based on flag, environment variable or something else
- Your `OAuthService` class has to ask factory to instantiate `OktaAuthStatusUnauthenticated` instance before initiating `authenticate`, `recoverPassword` and other flows

**Comment by nodediggity** [comment]
That makes perfect sense, thanks for the quick and super helpful response 👍
